### PR TITLE
Feature: Add append to array

### PR DESCRIPTION
**Pull request by kenjones-cisco**
Adds the ability to append a value to an array instead of having to
know the index of the values within the array.

Resolves: #17

### CODE REVIEW

**Comment by Rambatino** [comment]
Is this in the docs? I no can find.

**Comment by mikefarah** [comment]
http://mikefarah.github.io/yq/write/#appending-value-to-an-array-field

**Comment by Rambatino** [comment]
Thanks!

**Comment by Rambatino** [comment]
Can it support like passing a json object? The example is only one element, but I'd like to pass a nested structure to it.

**Comment by mikefarah** [comment]
Only one fields at a time:
```
yq n 'an.array[+].field.list[+].thing' apples
```

```
an:
  array:
  - field:
      list:
      - thing: apples
```

but you could use 
http://mikefarah.github.io/yq/write/#updating-multiple-values-with-a-script
to add multiples

**Comment by Rambatino** [comment]
Thanks @mikefarah!

**Pull request merged**
